version: '3.7'

services:
  web:
    image: nginx:1.23.2
    volumes:
    - ./templates:/etc/nginx/templates
    ports:
    - "8080:80"
    environment:
    - NGINX_PORT=80

  service1:
    build: 
      context: .
      dockerfile: ./dockerfiles/Dockerfile_service1
    volumes:
      - ./backend/service1:/app

  service2:
    build: 
      context: .
      dockerfile: ./dockerfiles/Dockerfile_service1
    volumes:
      - ./backend/service2:/app
    
